version: "3"

services:

  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "test"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      - cadastro-network
    restart: always

  cadastro-loja-api:
    container_name: cadastro-loja-api
    image: vinifontana/cadastroloja:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8090
      SERVER_NAME: Servidor_1
      TZ: "America/Sao_Paulo"
    ports:
        - "80:8090"
    depends_on:
      - mongo-db
    networks:
      - cadastro-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always


networks:
    cadastro-network:
        driver: bridge