version: "3"

services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "test"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    ports:
      - "27017:27017"
    networks:
      - cadastro-network
    restart: always

networks:
    cadastro-network:
        driver: bridge