version: "3"

services:
  load-balance:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cadastro-network
    depends_on:
      - cadastro-loja-api
      - cadastro-loja-api2

  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "test"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      - cadastro-network
    restart: always

  cadastro-loja-api:
    container_name: cadastro-loja-api
    image: vinifontana/cadastroloja:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8090
      SERVER_NAME: Servidor_1
      TZ: "America/Sao_Paulo"
    depends_on:
      - mongo-db
    networks:
      - cadastro-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

  cadastro-loja-api2:
    container_name: cadastro-loja-api2
    image: vinifontana/cadastroloja:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8091
      SERVER_NAME: Servidor_2
      TZ: "America/Sao_Paulo"
    depends_on:
      - mongo-db
    networks:
      - cadastro-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email vinicius.fontana@me.com -d viniciusfontana.com.br --agree-tos

networks:
    cadastro-network:
        driver: bridge